### ISSUE TITLE
Add one more example

### ISSUE THREAD

**Issue by ardok** [deoxxa/dotty#19]
I looked at the example: https://github.com/deoxxa/dotty/blob/master/example.js

`console.log(dotty.get(object, "a.b.z")); // undefined` <- that works

But can you add more examples like:

```
console.log(dotty.get(object, "a.b.z.z"));  // will this return undefined?
console.log(dotty.get(object, "a.b.z.z.z"));  // will this return undefined?
```

**Comment by stramel** [comment]
Added https://github.com/deoxxa/dotty/blob/8e157c2cd0508874c29cc80166ff4bd8ac5c46df/example.js#L22
