### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by danielelkabes** [deoxxa/dotty#25]
Hi team, 

I've contacted you via email, please let me know if you've received my email.

Thanks

**Comment by stramel** [comment]
Thanks for reaching out with that detail. I'm traveling today but I should be able to look at getting a fix in tomorrow or tonight.

**Comment by stramel** [comment]
@danielelkabes I have emailed you a version that hopefully has the vulnerability patched. Let me know if it works and I will patch that here.
